# Generated by Django 3.2.6 on 2021-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_whatsapp_group_event_descord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='whatsapp_group',
            new_name='descord',
        ),
        migrations.AddField(
            model_name='winners',
            name='social_link',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
