# Generated by Django 4.0.1 on 2022-05-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210823_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='game',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='event',
            name='descord',
        ),
    ]
