# Generated by Django 4.0.1 on 2022-05-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_game_event_year_remove_event_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='year',
            new_name='game',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='descord',
            field=models.CharField(default='', max_length=200),
        ),
    ]
