# Generated by Django 4.0.1 on 2022-05-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_year_event_game_event_date_time_event_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='game',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='descord',
        ),
    ]
