# Generated by Django 4.0.1 on 2022-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_game_banner_year_remove_banner_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descord',
            new_name='name_of_coordinator',
        ),
        migrations.AddField(
            model_name='event',
            name='judging',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='rule',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='sc_group_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
