# Generated by Django 4.0.1 on 2022-05-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_event_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='judging',
            field=models.TextField(default=''),
        ),
    ]
