# Generated by Django 4.0.1 on 2022-05-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_event_desc_alter_event_judging'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
