# Generated by Django 4.0.1 on 2022-05-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_event_venu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
