# Generated by Django 4.0.1 on 2022-05-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_event_reg_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reg_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
