# Generated by Django 4.0.1 on 2022-05-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_event_reg_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='desc',
        ),
        migrations.AddField(
            model_name='event',
            name='short_desc',
            field=models.TextField(default='', max_length=200),
        ),
    ]
