# Generated by Django 4.0.1 on 2022-05-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_event_desc_event_short_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='short_desc',
        ),
    ]
