# Generated by Django 4.0.1 on 2022-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_event_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.TextField(default='', max_length=200),
        ),
    ]
