# Generated by Django 4.0.1 on 2022-05-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_event_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='judging',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='rule',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
