# Generated by Django 4.0.1 on 2022-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_event_judging_alter_event_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinator_profile',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
