# Generated by Django 4.0.1 on 2022-05-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_event_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
